# Generated by Django 4.2.1 on 2023-06-22 07:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_rename_bid_id_bids_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comments",
            name="comment_id",
        ),
        migrations.RemoveField(
            model_name="auction_list",
            name="bid_id",
        ),
        migrations.DeleteModel(
            name="Bids",
        ),
        migrations.DeleteModel(
            name="Comments",
        ),
    ]
