# Generated by Django 4.2.1 on 2023-06-22 07:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_remove_comments_comment_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Auction_list",
        ),
    ]
