# Generated by Django 4.2.1 on 2023-06-22 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_delete_auction_list"),
    ]

    operations = [
        migrations.CreateModel(
            name="Catagory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("catagory_name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Auction_list",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("image_url", models.CharField(blank=True, max_length=1000, null=True)),
                ("desc", models.CharField(max_length=3000)),
                ("bid", models.FloatField()),
                ("is_active", models.BooleanField()),
                (
                    "catagory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auctions.catagory",
                    ),
                ),
            ],
        ),
    ]
