# Generated by Django 4.2.1 on 2023-06-22 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_catagory_auction_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction_list",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ownerUser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
