# Generated by Django 4.2.1 on 2023-06-22 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0008_alter_auction_list_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction_list",
            name="bid",
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name="auction_list",
            name="catagory",
            field=models.ForeignKey(
                default=" ",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cat",
                to="auctions.catagory",
            ),
        ),
        migrations.AlterField(
            model_name="auction_list",
            name="desc",
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name="auction_list",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ownerAuction",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Bids",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bids", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownerUser",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
