# Generated by Django 4.2.1 on 2023-06-22 17:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "auctions",
            "0009_alter_auction_list_bid_alter_auction_list_catagory_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="bids",
            old_name="bids",
            new_name="bid",
        ),
    ]
