# Generated by Django 4.2.1 on 2023-06-22 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0010_rename_bids_bids_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction_list",
            name="new_bid",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userBids",
                to="auctions.bids",
            ),
        ),
    ]
