# Generated by Django 4.2.1 on 2023-06-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0011_auction_list_new_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction_list",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="catagory",
            name="catagory_name",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
