# Generated by Django 4.2.1 on 2023-06-23 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0012_alter_auction_list_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction_list",
            name="new_bid",
        ),
        migrations.AlterField(
            model_name="auction_list",
            name="bid",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userBids",
                to="auctions.bids",
            ),
        ),
    ]
