# Generated by Django 4.2.1 on 2023-06-23 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0013_remove_auction_list_new_bid_alter_auction_list_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction_list",
            name="bid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userBids",
                to="auctions.bids",
            ),
        ),
        migrations.AlterField(
            model_name="auction_list",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ownerAuction",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
