# Generated by Django 4.2.1 on 2023-06-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0015_alter_bids_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="bids",
            name="bid_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
