# Generated by Django 4.2.1 on 2023-07-11 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0017_alter_auction_list_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction_list",
            name="catagory",
            field=models.ForeignKey(
                default=" ",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cat",
                to="auctions.catagory",
            ),
        ),
    ]
