# Generated by Django 4.2.1 on 2023-07-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0018_alter_auction_list_catagory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction_list",
            name="image_url",
            field=models.CharField(
                blank=True, default="media/placeholder.png", max_length=1000
            ),
        ),
    ]
