# Generated by Django 4.2.1 on 2023-07-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0023_alter_auction_list_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction_list",
            name="image_url",
            field=models.CharField(
                blank=True, default="images/placeholder.png", max_length=1000
            ),
        ),
    ]
