# Generated by Django 4.2.1 on 2023-07-25 05:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0025_alter_auction_list_image_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auction_list",
            options={"ordering": ["-created_on"]},
        ),
    ]
