# Generated by Django 4.2.1 on 2023-07-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0026_alter_auction_list_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="bids",
            name="auction_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
