# Generated by Django 4.2.1 on 2023-07-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0028_alter_bids_auction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bids",
            name="auction_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
