# Generated by Django 4.2.1 on 2023-08-11 06:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0031_alter_auction_list_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction_list",
            name="bookmarks",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="bookmark",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="auction_list",
            name="image_url",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
